included: # paths to include during linting. `--path` is ignored if present.
    - AlbertsonsCodeDemo
   - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - Sources/ExcludedFolder
    - Sources/ExcludedFile.swift
    - Sources/*/ExcludedFile.swift # Exclude files with a wildcard
